[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"
startCommand = "npm run start"
rootDirectory = "server"
watchPatterns = ["/server/**"]

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"

[environments]
[environments.production]
envs = { NODE_ENV = "production" }
