[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"
startCommand = "npm run start"
rootDir = "server"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
watchPaths = ["server/**"]

[envs]
NODE_ENV = "production"
